// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0an0ke4nccGca-EpogKgI6bkO0DfaNqc',
    appId: '1:103712354509:web:378cc71276d7ef35d27984',
    messagingSenderId: '103712354509',
    projectId: 'cashseven-94110',
    authDomain: 'cashseven-94110.firebaseapp.com',
    storageBucket: 'cashseven-94110.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfWLqzWfTstrpu6hxrtrrZG8tZ583qo8',
    appId: '1:103712354509:android:aa054455704e3392d27984',
    messagingSenderId: '103712354509',
    projectId: 'cashseven-94110',
    storageBucket: 'cashseven-94110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJGdo_QyBVvObJXH2VLRhuRs0hiNMd8c',
    appId: '1:103712354509:ios:cd61f5f8bd0f5dbbd27984',
    messagingSenderId: '103712354509',
    projectId: 'cashseven-94110',
    storageBucket: 'cashseven-94110.firebasestorage.app',
    androidClientId: '103712354509-f5ndfu94kim0k5ievnnsfau26iobeci0.apps.googleusercontent.com',
    iosClientId: '103712354509-8ubkvuro9dctvcdmei6ottq9fbr7b169.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyFive',
  );

}